// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flojlnzqivsziumuebgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsb2psbnpxaXZzeml1bXVlYmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDg2MDUsImV4cCI6MjA2ODUyNDYwNX0.vUOfYF0SL15vIZfQY4ezrz5JiKMK6zd7kOMrIhMMn4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});